version: "3.8"

services:
  cache:
    image: redis:alpine3.20
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./docker_data/redis:/data

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=hopp
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hopp
    ports:
      - "5432:5432"
    volumes:
      - ./docker_data/postgres:/var/lib/postgresql/data

  backend:
    image: hopp-backend
    restart: always
    ports:
      - "1926:1926"
    environment:
      - REDIS_URI=redis://cache:6379/0?protocol=3
      - DATABASE_DSN=postgres://hopp:password@db:5432/hopp?sslmode=disable
    env_file:
      - ../env-files/.env.local
    depends_on:
      - cache
      - db
    volumes:
      - ../certs/:/app/certs/
volumes:
  cache:
    driver: local
