name: hopp_core CI

on:
  workflow_run:
    workflows: ["pre-commit"]
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-files:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      core-changed: ${{ steps.filter.outputs.core }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch the commit that triggered the workflow and its parent
          fetch-depth: 2
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Check for changes in core/
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ github.event.workflow_run.head_sha }}^
          filters: |
            core:
              - 'core/**'

  fmt:
    runs-on: ubuntu-latest
    needs: check-files
    if: ${{ needs.check-files.outputs.core-changed == 'true' || github.event_name == 'workflow_dispatch' }}

    defaults:
      run:
        working-directory: core

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Run rustfmt
        run: cargo fmt --all -- --check

  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: check-files
    if: ${{ needs.check-files.outputs.core-changed == 'true' || github.event_name == 'workflow_dispatch' }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin

    defaults:
      run:
        working-directory: core

    env:
      HOPP_CORE_BIN_DEFAULT: "1"

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Cache Cargo builds
        uses: Swatinem/rust-cache@v2

      - name: Set XCode
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          sudo xcode-select -s "/Applications/Xcode_16.2.app"

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Lint (clippy)
        run: cargo clippy --target ${{ matrix.target }} --all-features -- -D warnings
